services:
  frontend:
    container_name: portfolio-frontend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - default
      - proxy_net

networks:
  proxy_net:
    external: true
